app/Admin/controllers.py
from app import database
from app.User.models import User
from app.User import (
    get_user_with_id,
    update_admin_status,
    update_disabled_status,
    delete_user_with_id
)
from flask import (
    Blueprint,
    request,
    jsonify,
    redirect,
    url_for,
    render_template
)
from flask_login import (
    login_required,
    current_user
)
from datatables import (
    ColumnDT,
    DataTables
)

# blueprint definition
_admin = Blueprint('admin_bp', __name__, url_prefix='/admin')


# routes #=====================================================================

@_admin.route('/data')
@login_required
def data():
    """Return server side data"""
    # defining columns
    columns = [
        ColumnDT(User.id),
        ColumnDT(User.first_name),
        ColumnDT(User.last_name),
        ColumnDT(User.email),
        ColumnDT(User.username),
        ColumnDT(User.admin),
        ColumnDT(User.disabled)
    ]

    # defining initial query
    query = database.session.query().select_from(User)

    # GET parameters
    params = request.args.to_dict()

    # instantiating a DataTable for the query and table needed
    rowTable = DataTables(params, query, columns)

    # returns what is needed by DataTable
    return jsonify(rowTable.output_result())


@_admin.route('/manage_users', methods=['GET', 'POST'])
@login_required
def manage_users():
    """If user is admin lists with user data, redirects to dashboard if not"""

    # Check if the current user has admin privileges
    if not current_user.admin:
        return redirect(url_for('main_bp.dashboard'))

    if request.method == 'POST':
        if request.form["operation"] == "admin":
            return redirect(url_for('admin_bp.update_admin'), code=307)
        elif request.form["operation"] == "disable":
            return redirect(url_for('admin_bp.update_disabled'), code=307)
        elif request.form["operation"] == "delete":
            return redirect(url_for('admin_bp.delete'), code=307)

    return render_template('Admin/manage_users.html')


@_admin.route('/manage_users/update_admin', methods=['POST'])
def update_admin():
    selected_user = request.form.getlist('user_id[]')
    for user in selected_user:
        admin = get_user_with_id(int(user)).admin
        update_admin_status(int(user), not bool(admin))
    return redirect(request.referrer)


@_admin.route('/manage_users/update_disabled', methods=['POST'])
def update_disabled():
    selected_user = request.form.getlist('user_id[]')
    for user in selected_user:
        disabled = get_user_with_id(int(user)).disabled
        update_disabled_status(int(user), not bool(disabled))
    return redirect(request.referrer)


@_admin.route('/manage_users/delete', methods=['POST'])
def delete():
    selected_user = request.form.getlist('user_id[]')
    for user in selected_user:
        delete_user_with_id(int(user))
    return redirect(request.referrer)

app/Main/controllers.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from app.Data.Import.forms import UploadForm
from app.User.forms import EditForm
from app.Project.forms import ProjectForm, ShareForm
from app.Project.operations import get_all_projects_for_user

_main = Blueprint('main_bp', __name__)


@_main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))
    return redirect(url_for('user_bp.login'))


@_main.route('/dashboard')
@login_required
def dashboard():
    projects = get_all_projects_for_user(current_user.id)

    upload_form = UploadForm()
    project_form = ProjectForm()
    share_form = ShareForm()
    edit_form = EditForm()

    return render_template(
        'Main/dashboard.html',
        projects=projects,
        upload_form=upload_form,
        project_form=project_form,
        share_form=share_form,
        edit_form=edit_form
    )

app/Project/controllers.py
from flask import Blueprint, redirect, url_for, request, flash
from flask_login import login_required, current_user
from .forms import ProjectForm, ShareForm
from app.User import get_user_with_username
from .operations import (
    create_project,
    share_project,
    update_project_with_id,
    delete_project_with_id
)


_project = Blueprint('project_bp', __name__, url_prefix='/project')


@_project.route('/create', methods=['POST'])
@login_required
def create():
    form = ProjectForm()
    if form.validate_on_submit():
        create_project(
            form.name.data,
            form.description.data,
            current_user.id
        )
        flash('New project created successfully!', 'success')
    return redirect(url_for('main_bp.dashboard'))


@_project.route('/update', methods=['POST'])
@login_required
def update():
    form = ProjectForm()
    if form.validate_on_submit():
        update_project_with_id(
            request.form['project_id'],
            form.name.data,
            form.description.data
        )
        flash('Project updated successfully!', 'success')
    return redirect(url_for('main_bp.dashboard'))


@_project.route('/delete', methods=['POST'])
@login_required
def delete():
    delete_project_with_id(
        request.form['project_id'],
        current_user.id
    )
    flash('Project deleted successfully!', 'success')
    return redirect(url_for('main_bp.dashboard'))


@_project.route('/share', methods=['POST'])
@login_required
def share():
    form = ShareForm()
    if form.validate_on_submit():
        submitted_user = get_user_with_username(form.username.data)
        if submitted_user is not None:
            try:
                share_project(
                    request.form['project_id'],
                    submitted_user.id
                )
                flash(
                    'The project was succesfully shared with {}.'.
                    format(form.username.data),
                    'success'
                )
            except RuntimeError:
                flash(
                    '{} already has access to this project.'.
                    format(form.username.data),
                    'warning'
                )
        else:
            flash(
                'No user with username: {}.'.format(form.username.data),
                'danger'
            )
    return redirect(url_for('main_bp.dashboard'))

app/User/controllers.py
from app import login_manager as lm
from .forms import (
    SignUpForm,
    LoginForm,
    EditForm
)
from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    jsonify,
    request
)
from flask_login import (
    login_user,
    logout_user,
    login_required,
    current_user
)
from .operations import (
    get_user_with_id,
    get_user_with_username,
    create_user,
    validate_login_credentials,
    update_user_with_id
)
from .models import User

_user = Blueprint('user_bp', __name__, url_prefix='/user')
lm.login_view = 'user_bp.login'


@lm.user_loader
def load_user(user_id):
    return get_user_with_id(user_id)


@_user.route('/autocomplete', methods=['GET'])
def autocomplete():
    users = User.query.with_entities(User.username).all()
    return jsonify(users)


@_user.route('/signup', methods=['POST'])
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        try:
            create_user(
                form.first_name.data,
                form.last_name.data,
                form.email.data,
                form.username.data,
                form.password.data
            )
            flash('You have been registered and can now log in.', 'success')
        except RuntimeError as error:
            flash(str(error), 'danger')
    return redirect(url_for('user_bp.login'))


@_user.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    signup_form = SignUpForm()

    if login_form.validate_on_submit():
        result = validate_login_credentials(
            login_form.username.data,
            login_form.password.data
        )
        if result[0] is True:
            user = get_user_with_username(login_form.username.data)
            login_user(user)
            return redirect(url_for('main_bp.dashboard'))
        else:
            flash(result[1], 'danger')

    return render_template('User/login.html',
                           login_form=login_form,
                           signup_form=signup_form
                           )


@_user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.login'))


@_user.route('/update', methods=['POST'])
@login_required
def update():
    form = EditForm()
    if form.validate_on_submit():
        if not validate_login_credentials(
                current_user.username,
                form.current_password.data)[0]:
            flash('Current password is not correct.', 'danger')
        try:
            update_user_with_id(
                current_user.id,
                form.first_name.data,
                form.last_name.data,
                form.email.data,
                form.username.data,
                form.new_password.data
            )
            flash('Your account information has been updated.', 'success')
        except RuntimeError as error:
            flash(str(error), 'danger')
    return redirect(request.referrer)

app/_main/controllers.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from app._data.helpers import get_datasets, get_projects
from app._data.forms import UploadForm, ProjectForm, ShareForm

_main = Blueprint('main_bp', __name__)


@_main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))
    return redirect(url_for('user_bp.login'))


@_main.route('/dashboard')
@login_required
def dashboard():
    projects = get_projects(current_user.id, True)
    datasets = get_datasets(current_user.id)

    upload_form = UploadForm()
    project_form = ProjectForm()
    share_form = ShareForm()

    return render_template(
        '_main/dashboard.html',
        projects=projects,
        datasets=datasets,
        upload_form=upload_form,
        project_form=project_form,
        share_form=share_form
    )

app/templates/Main/dashboard.html
{% extends "layout/main.html" %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/Main/dashboard.css')}}">
{% endblock %}

{% block sidebar_content %}
    <ul class="nav nav-pills flex-column">
        <!-- User banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-user"></i>
                User
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link"
               href="#edit-profile-modal"
               data-toggle="modal"
               data-target="#edit-profile-modal">
                <i class="fas fa-edit "></i>
                Edit Profile
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('user_bp.logout') }}">
                <i class="fas fa-sign-out-alt "></i>
                Sign Out
            </a>
        </li>
        {% if current_user.admin %}
            <!-- Admin banner -->
            <li class="nav-item">
                <a class="nav-link not-clickable active" href="#">
                    <i class="fas fa-key"></i>
                    Admin
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link sidebar-link" href="{{ url_for('admin_bp.manage_users') }}">
                    <i class="fas fa-users"></i>
                    Manage Users
                </a>
            </li>
        {% endif %}
        <!-- Projects banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-sitemap"></i>
                Projects
            </a>
        </li>
        <!-- Projects -->
        {% for project in projects %}
            <!-- Project info toggle -->
            <li class="nav-item">
                <a class="nav-link sidebar-link" data-toggle="collapse"
                   href="#sidebar-{{ project.id }}-info">
                    <i class="fas fa-caret-right fa-fw" id="sidebar-{{ project.id }}-toggle"></i>
                    {{ project.name }}
                </a>
            </li>
            <!-- Collapsable project info card -->
            <div class="collapse sidebar-collapse" id="sidebar-{{ project.id }}-info">
                <div class="card card-body sidebar-card">
                    <h6>Description:</h6>
                    {{ project.description }}
                    <hr/>
                    <div class="row-fluid inline action-icons">
                        <!-- Open project button -->
                        <a href="{{ url_for('view_bp.view', project_id=project.id) }}">
                            <i class="fas fa-folder-open"></i>
                        </a>
                        {% if project.owner_id == current_user.id %}
                            <!-- Edit project button -->
                            <a href="#edit-project-modal" data-toggle="modal"
                               data-target="#edit-project-modal"
                               data-projectid="{{ project.id }}"
                               data-title="{{ project.name }}"
                               data-description="{{ project.description }}">
                                <i class="fas fa-edit"></i>
                            </a>
                        {% endif %}
                        <!-- Delete project button -->
                        <form id="delete-form-{{ project.id }}"
                              action="{{ url_for('project_bp.delete') }}"
                              method="POST">
                            <input type="hidden" name="project_id"
                                   value="{{ project.id }}">
                            <a href="#" onclick="document.getElementById('delete-form-{{ project.id }}').submit()">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </form>
                        {% if project.owner_id == current_user.id %}
                        <!-- Share project button -->
                            <a href="#share-project-modal" data-toggle="modal"
                               data-target="#share-project-modal"
                               data-projectid="{{ project.id }}">
                                <i class="fas fa-share-alt"></i>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock %}

{% block main_content %}
    <div class="jumbotron">
        {% if current_user.first_name %}
            <h1 class="display-4">Hello, {{ current_user.first_name }}!</h1>
        {% else%}
            <h1 class="display-4">Hello there!</h1>
        {% endif %}
        <p class="lead">
            Welcome to our data wrangling web application!
        </p>
        <hr class="my-4">
        <p>
            Continue working on one of your existing projects by clicking on them on the left, or create a new one by pressing the button below.
        </p>
        <p>
            <a class="btn btn-outline-success btn-lg" href="#" data-toggle="modal" data-target="#create-project-modal" role="button">
                <i class="fas fa-plus"></i>
                Create Project
            </a>
        </p>
    </div>
{% endblock %}

{% block modals %}
    {% include 'Project/create_modal.html' %}
    {% include 'Project/edit_modal.html' %}
    {% include 'Project/share_modal.html' %}
    {% include 'User/edit_modal.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
	<script src="{{ url_for('static', filename='js/layout/navbar_side.js') }}"></script>
	<script src="{{ url_for('static', filename='js/Project/edit_modal.js') }}"></script>
	<script src="{{ url_for('static', filename='js/Project/share_modal.js') }}"></script>
{% endblock %}