app/User/models.py
from app import database as db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash


class User(db.Model, UserMixin):
    """Represents table holding user data in our database"""

    # Table name to be used in database
    # If not provided class name is used which is a problem when using
    # postgres because user is a reserved keyword
    __tablename__ = 'user_data'

    # Table columns
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    first_name = db.Column(db.String(25))
    last_name = db.Column(db.String(25))
    email = db.Column(db.String(50), unique=True, nullable=False)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)
    admin = db.Column(db.Boolean(), default=0)
    disabled = db.Column(db.Boolean(), default=0)

    # User is parent of action, thus this relationship helper class
    actions = db.relationship(
        'Action',
        backref='user',
        lazy='dynamic'
    )

    def __init__(self, fname, lname, email, uname, password):
        """Initializes a user instance"""
        self.first_name = fname
        self.last_name = lname
        self.email = email
        self.username = uname
        self.password = generate_password_hash(password, method='sha256')

app/User/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, BooleanField, HiddenField
from wtforms.validators import InputRequired, Email, Length, EqualTo, Optional


class SignUpForm(FlaskForm):
    """Represents form used for user signup"""
    first_name = StringField(
        'First name',
        validators=[Length(max=25)]
    )
    last_name = StringField(
        'Last name',
        validators=[Length(max=25)]
    )
    email = StringField(
        'Email',
        validators=[InputRequired(), Email('Invalid email'), Length(max=50)]
    )
    confirm_email = StringField(
        'Confirm email',
        validators=[EqualTo('email')]
    )
    username = StringField(
        'Username',
        validators=[InputRequired(), Length(min=4, max=20)]
    )
    password = PasswordField(
        'Password',
        validators=[InputRequired(), Length(min=4, max=80)]
    )
    confirm_password = PasswordField(
        'Confirm password',
        validators=[EqualTo('password')]
    )


class LoginForm(FlaskForm):
    """Represents form used for user login"""
    username = StringField(
        'Username',
        validators=[InputRequired()]
    )
    password = PasswordField(
        'Password',
        validators=[InputRequired()]
    )


class EditForm(FlaskForm):
    """Represents form used for edit user info"""
    first_name = StringField(
        'First Name',
        validators=[Optional(), Length(max=25)]
    )
    last_name = StringField(
        'Last name',
        validators=[Optional(), Length(max=25)]
    )
    email = StringField(
        'Email',
        validators=[Optional(), Email('Invalid email'), Length(max=50)]
    )
    username = StringField(
        'Username',
        validators=[Optional(), Length(min=4, max=20)]
    )
    new_password = PasswordField(
        'New password',
        validators=[Optional(), Length(min=4, max=80)]
    )
    confirm_password = PasswordField(
        'Confirm new password',
        validators=[EqualTo('new_password')]
    )
    current_password = PasswordField(
        'Current password',
        validators=[InputRequired()]
    )

app/User/__init__.py
from .operations import (
    create_user,
    get_user_with_username,
    get_user_with_id,
    delete_user_with_username,
    delete_user_with_id,
    update_user_with_id,
    update_admin_status,
    update_disabled_status,
    validate_login_credentials,
    init_admin
)

__all__ = [
    'create_user',
    'get_user_with_username',
    'get_user_with_id',
    'delete_user_with_username',
    'delete_user_with_id',
    'update_user_with_id',
    'update_admin_status',
    'update_disabled_status',
    'validate_login_credentials',
    'init_admin'
]

app/User/controllers.py
from app import login_manager as lm
from .forms import (
    SignUpForm,
    LoginForm,
    EditForm
)
from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    url_for,
    jsonify,
    request
)
from flask_login import (
    login_user,
    logout_user,
    login_required,
    current_user
)
from .operations import (
    get_user_with_id,
    get_user_with_username,
    create_user,
    validate_login_credentials,
    update_user_with_id
)
from .models import User

_user = Blueprint('user_bp', __name__, url_prefix='/user')
lm.login_view = 'user_bp.login'


@lm.user_loader
def load_user(user_id):
    return get_user_with_id(user_id)


@_user.route('/autocomplete', methods=['GET'])
def autocomplete():
    users = User.query.with_entities(User.username).all()
    return jsonify(users)


@_user.route('/signup', methods=['POST'])
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        try:
            create_user(
                form.first_name.data,
                form.last_name.data,
                form.email.data,
                form.username.data,
                form.password.data
            )
            flash('You have been registered and can now log in.', 'success')
        except RuntimeError as error:
            flash(str(error), 'danger')
    return redirect(url_for('user_bp.login'))


@_user.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    signup_form = SignUpForm()

    if login_form.validate_on_submit():
        result = validate_login_credentials(
            login_form.username.data,
            login_form.password.data
        )
        if result[0] is True:
            user = get_user_with_username(login_form.username.data)
            login_user(user)
            return redirect(url_for('main_bp.dashboard'))
        else:
            flash(result[1], 'danger')

    return render_template('User/login.html',
                           login_form=login_form,
                           signup_form=signup_form
                           )


@_user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user_bp.login'))


@_user.route('/update', methods=['POST'])
@login_required
def update():
    form = EditForm()
    if form.validate_on_submit():
        if not validate_login_credentials(
                current_user.username,
                form.current_password.data)[0]:
            flash('Current password is not correct.', 'danger')
        try:
            update_user_with_id(
                current_user.id,
                form.first_name.data,
                form.last_name.data,
                form.email.data,
                form.username.data,
                form.new_password.data
            )
            flash('Your account information has been updated.', 'success')
        except RuntimeError as error:
            flash(str(error), 'danger')
    return redirect(request.referrer)

app/templates/User/edit_modal.html
<div class="modal fade" id="edit-profile-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Profile:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
		<form method="POST" action="{{ url_for('user_bp.update') }}">
            <div class="modal-body">
                {{ edit_form.hidden_tag() }}
                {{ wtf.form_field(edit_form.first_name, value=current_user.first_name) }}
                {{ wtf.form_field(edit_form.last_name, value=current_user.last_name) }}
                {{ wtf.form_field(edit_form.email, value=current_user.email) }}
                {{ wtf.form_field(edit_form.username, value=current_user.username) }}
                {{ wtf.form_field(edit_form.new_password) }}
                {{ wtf.form_field(edit_form.confirm_password) }}
                {{ wtf.form_field(edit_form.current_password) }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </form>
    </div>
  </div>
</div>

app/templates/User/login.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    ADReM - Data Wrangler
{% endblock %}

{% block styles %}
	{{ super() }}
	<link rel="stylesheet" href="{{url_for('static', filename='css/User/signin.css')}}">
{% endblock %}

{% block body_attribs %}
    class="text-center"
{% endblock %}

{% block content %}
    <form class="form-signin" action="{{ url_for('user_bp.login') }}" method="POST">
        <img class="mb-4"
             src="{{ url_for('static', filename='img/logo.svg') }}"
             alt="" width="150" height="150">
        <h3 class="mb-3 font-weight-normal">Data Wrangler</h3>
        {% include 'layout/flash_messages.html' %}
        {{ login_form.hidden_tag() }}
        {{ login_form.username(class="form-control", placeholder="Username", type="username") }}
        {{ login_form.password(class="form-control", placeholder="Password", type="password") }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <h7>Don't have an account? <a href="#signup-modal" data-toggle="modal" data-target="#signup-modal">Register here.</a></h7>
        <p class="mt-5 mb-3 text-muted">&copy; Group4</p>
    </form>


    <div class="modal fade" id="signup-modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Register:</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form method="POST" action="{{ url_for('user_bp.signup') }}">
                <div class="modal-body">
                    {{ signup_form.hidden_tag() }}
                    <div class="row">
                        <div class="col-md-6">
                        {{ signup_form.username(class="form-control signup-forms", placeholder="Username*") }}
                        </div>
                        <div class="col-md-6">
                            <h6 class="signup-forms-fix text-muted">* = Required</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                        {{ signup_form.first_name(class="form-control signup-forms", placeholder="First Name") }}
                        </div>
                        <div class="col-md-6">
                        {{ signup_form.last_name(class="form-control signup-forms", placeholder="Last Name") }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                        {{ signup_form.email(class="form-control signup-forms", placeholder="Email*") }}
                        </div>
                        <div class="col-md-6">
                        {{ signup_form.confirm_email(class="form-control signup-forms", placeholder="Confirm Email") }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                        {{ signup_form.password(class="form-control signup-forms", placeholder="Password*") }}
                        </div>
                        <div class="col-md-6">
                        {{ signup_form.confirm_password(class="form-control signup-forms", placeholder="Confirm Password") }}
                        </div>
                    </div>
                    <hr/>
                    <hr/>
                    <div class="row">
                        <button type="submit" class="btn btn-block btn-success fixed-bottom">Submit</button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}