app/Data/models.py
from app import database as db
from datetime import datetime


class Dataset(db.Model):
    """
    Represents table holding dataset info
    """

    __tablename__ = 'dataset'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    original_data = db.Column(db.String(50), unique=True, nullable=False)
    working_copy = db.Column(db.String(50), unique=True, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    # View is parent of action, thus this relationship helper class
    actions = db.relationship(
        'Action',
        backref='dataset',
        lazy='dynamic',
        passive_deletes=True
    )

    # Dataset is child of project, thus this foreign key
    project_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'project.id',
            ondelete='CASCADE'
        )
    )

    def __init__(self, name, original, working, description, project):
        self.name = name
        self.original_data = original
        self.working_copy = working
        self.description = description
        self.project_id = project


class Action(db.Model):
    """ Vieze docstring """

    __tablename__ = 'action'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    time = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    # Action is child of view, thus this foreign key
    dataset_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'dataset.id',
            ondelete='CASCADE'
        )
        , nullable=False
    )

    # Action is child of user, thus this foreign key
    user_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user_data.id',
            ondelete='SET NULL')
    )

    def __init__(self, description, dataset_id, user_id):
        self.description = description
        self.dataset_id = dataset_id
        self.user_id = user_id

app/Data/Import/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FileField, TextAreaField
from wtforms.validators import InputRequired, Length


class UploadForm(FlaskForm):
    """docstring for UploadForm"""

    file = FileField('File (.csv, .zip or .dump)',
                     validators=[InputRequired()]
                     )
    name = StringField('Name', validators=[InputRequired(), Length(max=50)])
    description = TextAreaField('Description',
                                validators=[InputRequired(), Length(max=255)])


class EditForm(FlaskForm):
    """docstring for UploadForm"""

    name = StringField('Name', validators=[InputRequired(), Length(max=50)])
    description = TextAreaField('Description',
                                validators=[InputRequired(), Length(max=255)])

app/Data/View/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired, Length


class DeleteForm(FlaskForm):
    """Represents form used for sharing projects"""
    condition = StringField(
        '',
        id='condition',
        validators=[InputRequired()]
    )

app/Data/Import/controllers.py
from flask import Blueprint, render_template, redirect, url_for, request, flash,jsonify
from .forms import UploadForm, EditForm
from .operations import upload_csv, upload_joined, update_dataset_with_id, delete_dataset_with_id
from flask_login import login_required
import zipfile as zf
import os
from app.Project.operations import get_project_with_id
from app.Data.helpers import extract_tables_from_dump
from app import database as db
from sqlalchemy.sql import text
from app.Data.models import Dataset
import pandas as pd

import re
import sys

_upload = Blueprint('upload_bp', __name__, url_prefix='/data/upload')


@_upload.route('/', methods=['GET', 'POST'])
@login_required
def upload():

    project_id = request.args.get('project_id')

    # Clear any files from previous (unfinished) uploads
    filelist = os.listdir('./file_queue/')
    for f in filelist:
        if not f.startswith('.'):
            os.remove(os.path.join('./file_queue/', f))

    form = UploadForm()
    if form.validate_on_submit():
        filename = request.files['file'].filename
        if filename.lower()[-4:] == '.csv':
            return redirect(
                url_for(
                    'upload_bp.csv',
                    project_id=project_id
                ),
                code=308
            )
        elif filename.lower()[-4:] == '.zip':
            return redirect(
                url_for(
                    'upload_bp.zip',
                    project_id=project_id
                        ),
                code=308
            )
        elif filename.lower()[-4:] == '.sql':
            return redirect(url_for('upload_bp.dump', project_id=project_id), code=308)
        elif filename.lower()[-5:] == '.dump':
            return redirect(url_for('upload_bp.dump', project_id=project_id), code=308)
        else:
            flash('Filetype not supported.', 'danger')

    return redirect(url_for('view_bp.view', project_id=project_id))


@_upload.route('/csv', methods=['POST'])
@login_required
def csv():
    form = UploadForm()
    project_id = request.args.get('project_id')
    try:
        upload_csv(
            form.name.data,
            form.description.data,
            request.files['file'],
            project_id
        )
    except Exception:
        flash('An error occured while uploading your file.', 'danger')
    else:
        flash('Your file has been uploaded successfully.', 'success')
    return redirect(url_for('view_bp.view', project_id=project_id))


@_upload.route('/zip', methods=['POST'])
@login_required
def zip():
    form = UploadForm()
    project_id = request.args.get('project_id')
    if request.files.get('file', None) is None:
        for submission in request.form:
            if submission.startswith('checkbox-'):
                filename = submission.replace('checkbox-', '')
                upload_csv(
                    request.form['name-' + filename],
                    request.form['description-' + filename],
                    './file_queue/' + filename,
                    project_id
                )
            elif submission.startswith('join-type'):
                number = submission[-1]
                upload_joined(
                    request.form[submission],
                    request.form['join-name' + number],
                    request.form['join-description' + number],
                    request.form['file-left' + number],
                    request.form['column-left' + number],
                    request.form['file-right' + number],
                    request.form['column-right' + number],
                    project_id
                )
        flash('Your file has been uploaded.', 'success')
        return redirect(url_for('upload_bp.upload', project_id=project_id))

    else:
        edit_form = EditForm()
        with zf.ZipFile(request.files['file'], 'r') as csv_zip:
            files = []
            for file in csv_zip.namelist():
                if file.find('/') == -1:
                    files.append(file)
            file_to_column = {}
            for file in files:
                csv_zip.extract(file, path='./file_queue')
                data = open('./file_queue/{}'.format(file), 'r')
                cscolumns = data.readline()
                columns = [x.strip() for x in cscolumns.split(',')]
                file_to_column[file] = columns
                data.close()

            return render_template(
                'Data/Import/zip_join.html',
                name=form.name.data,
                description=form.description.data,
                project=get_project_with_id(project_id),
                files=files,
                edit_form=edit_form
            )


@_upload.route('/dump', methods=['POST'])
@login_required
def dump():
    # TODO: implement .sql/.dump upload
    form = UploadForm()
    project_id = request.args.get('project_id')
    print(project_id)
    name = form.name.data
    description = form.description.data
    file = request.files['file'].read()
    #tabledict: contains table names in dump as keys, newly generated, non overlapping names as values
    tabledict = extract_tables_from_dump(file)
    for old_table_name in tabledict:
        file = re.sub(old_table_name, tabledict[old_table_name], file)
    file = re.sub('`', '', file)
    file =  re.sub(r'VARCHAR ?\([\d]+\)', "TEXT", file, flags=re.IGNORECASE)
    # file = re.sub('auto_increment', 'serial', file)
    # file =  re.sub(r'int ?\([\d]+\)', "int", file, flags=re.IGNORECASE)
    # file =  re.sub(r'mediumtext', "text", file, flags=re.IGNORECASE)
    # file =  re.sub(r'[^\) ?];', "", file, flags=re.IGNORECASE)
    try:
        statement = str(file)#.decode("utf-8")
        result = db.session.execute(statement)
        db.session.commit()
    except:
        print("Unexpected error:", sys.exc_info()[0])
        raise

    for old_table_name in tabledict:
        table_name = tabledict[old_table_name]
        original = table_name
        working_copy = "wc" + table_name[2:]
        #result = s.execute('SELECT * FROM my_table WHERE my_column = :val', {'val': 5})
        connection = db.session.connection()

        # connection.execute(statement, {'name':table_name, 'og':original})
        # db.session.commit()
        # connection.execute(text('CREATE TABLE :wc AS TABLE :og'), {'wc':working_copy, 'og':original})
        dataframe = pd.read_sql_table(original, db.engine)
        dataframe.to_sql(name=original, con=db.engine, if_exists="replace")
        dataframe.to_sql(name=working_copy, con=db.engine, if_exists="replace")

        # db.session.execute(text('alter table '+original+' drop constraint '+original+'_pkey'))
        # db.session.execute(text('CREATE TABLE '+working_copy+' AS TABLE '+original))#, {'wc':working_copy, 'og':original})
        # db.session.commit()
        # db.session.execute(text('ALTER TABLE '+working_copy+' ADD COLUMN index SERIAL PRIMARY KEY;'))
        # db.session.execute(text('ALTER TABLE '+original+' ADD COLUMN index SERIAL PRIMARY KEY;'))
        # db.session.commit()

        # result_dataframe.to_sql(name=original, con=db_engine, if_exists="fail")
        # result_dataframe.to_sql(name=working_copy, con=db_engine, if_exists="fail")

        new_dataset = Dataset(
            name,
            original,
            working_copy,
            description,
            project_id
        )
        db.session.add(new_dataset)
        db.session.commit()

    #TODO give user interface with option to join tables, do that and then delete the table you just created
    #extract columns

    return redirect(request.referrer)


@_upload.route('/update', methods=['POST'])
@login_required
def update():
    form = EditForm()
    if form.validate_on_submit():
        update_dataset_with_id(
            request.form['dataset_id'],
            form.name.data,
            form.description.data
        )
        flash('Project updated successfully!', 'success')
    return redirect(request.referrer)


@_upload.route('/delete', methods=['POST'])
@login_required
def delete():
    delete_dataset_with_id(
        request.form['dataset_id']
    )
    flash('Project deleted successfully!', 'success')
    return redirect(request.referrer)


@_upload.route('/extract_columns', methods=['GET'])
@login_required
def extract_columns():
    files = os.listdir('./file_queue/')
    file_to_column = {}
    for file in files:
        data = open('./file_queue/{}'.format(file), 'r')
        cscolumns = data.readline()
        columns = [x.strip('\"').strip('\'') for x in cscolumns.split(',')]
        file_to_column[file] = columns
        data.close()
    return jsonify(file_to_column)

app/templates/Data/Import/edit_modal.html
<div class="modal fade" id="edit-dataset-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit dataset info:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
		<form method="POST" action="{{ url_for('upload_bp.update') }}">
            <div class="modal-body">
                <input type="hidden" id="edit-hidden-id" name="dataset_id" value="">
                {{ edit_form.hidden_tag() }}
                {{ wtf.form_field(edit_form.name, id='edit-title') }}
                {{ wtf.form_field(edit_form.description, id='edit-desc') }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </form>
    </div>
  </div>
</div>

app/templates/Data/Import/upload.html
{% extends "layout/main.html" %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block sidebar_content %}
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('main_bp.dashboard') }}">
                <i class="fas fa-home fa-fw"></i>
                Return to Dashboard
            </a>
        </li>
        <!-- Project banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-sitemap fa-fw"></i>
                Project
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link current-section" href="{{ url_for('view_bp.view', project_id=project.id) }}">
                <i class="fas fa-upload fa-fw"></i>
                Upload data
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('view_bp.join', project_id=project.id) }}">
                <i class="fas fa-random fa-rotate-270 fa-fw"></i>
                Merge data
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('view_bp.compare_view', project_id=project.id) }}">
                <i class="fas fa-chart-pie fa-fw"></i>
                Compare view
            </a>
        </li>
        <!-- Datasets banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-database fa-fw"></i>
                Datasets
            </a>
        </li>
    {% for dataset in project.datasets %}
        <li class="nav-item">
            <a class="nav-link sidebar-link" data-toggle="collapse"
               href="#sidebar-{{ dataset.id }}-info">
                <i class="fas fa-caret-right fa-fw" id="sidebar-{{ dataset.id }}-toggle"></i>
                {{ dataset.name }}
            </a>
        </li>
        <!-- Collapsable dataset info card -->
        <div class="collapse sidebar-collapse" id="sidebar-{{ dataset.id }}-info">
            <div class="card card-body sidebar-card">
                <h6>Description:</h6>
                {{ dataset.description }}
                <hr/>
                <div class="row-fluid inline action-icons">
                    <!-- Open project button -->
                    <a href="{{ url_for('view_bp.view', dataset_id=dataset.id) }}">
                        <i class="fas fa-folder-open"></i>
                    </a>
                    <!-- Edit project button -->
                    <a href="#edit-dataset-modal" data-toggle="modal"
                       data-target="#edit-dataset-modal"
                       data-projectid="{{ dataset.id }}"
                       data-title="{{ dataset.name }}"
                       data-description="{{ dataset.description }}">
                        <i class="fas fa-edit"></i>
                    </a>
                    <!-- Delete project button -->
                    <form id="delete-form-{{ dataset.id }}"
                          action="{{ url_for('upload_bp.delete', dataset_id=dataset.id) }}"
                          method="POST">
                        <input type="hidden" name="dataset_id"
                               value="{{ dataset.id }}">
                        <a href="#" onclick="document.getElementById('delete-form-{{ dataset.id }}').submit()">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
    </ul>
{% endblock %}

{% block main_content %}
    <div class="jumbotron">
        <h1 class="display-4">Project: {{ project.name }}</h1>
        <p class="lead">
            Description:
        </p>
        <p>
            {{ project.description }}
        </p>
        <hr class="my-4">
        <p class="text-muted">
            Select one of your existing datasets on the left to continue working on them, or upload new data below.
        </p>
        <div class="col-md-5">
            <form method="POST" action="{{ url_for('upload_bp.upload', project_id=project.id) }}" enctype="multipart/form-data">
                    {{ upload_form.hidden_tag() }}
                    {{ wtf.form_field(upload_form.file) }}
                    {{ wtf.form_field(upload_form.name) }}
                    {{ wtf.form_field(upload_form.description) }}
                    <button class="btn btn-success">
                        <i id="testing" class="fas fa-upload fa-fw"></i>
                        Upload
                    </button>
            </form>
        </div>
    </div>
{% endblock %}

{% block modals %}
{% include 'Data/Import/edit_modal.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
	<script src="{{ url_for('static', filename='js/layout/navbar_side.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Data/Import/edit_modal.js') }}"></script>
{% endblock %}

app/templates/Data/Import/zip_join.html
{% extends "layout/main.html" %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block sidebar_content %}
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('main_bp.dashboard') }}">
                <i class="fas fa-home fa-fw"></i>
                Return to Dashboard
            </a>
        </li>
        <!-- Project banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-sitemap fa-fw"></i>
                Project
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link current-section" href="{{ url_for('view_bp.view', project_id=project.id) }}">
                <i class="fas fa-upload fa-fw"></i>
                Upload data
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('view_bp.join', project_id=project.id) }}">
                <i class="fas fa-random fa-rotate-270 fa-fw"></i>
                Merge data
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link sidebar-link" href="{{ url_for('view_bp.compare_view', project_id=project.id) }}">
                <i class="fas fa-chart-pie fa-fw"></i>
                Compare view
            </a>
        </li>
        <!-- Datasets banner -->
        <li class="nav-item">
            <a class="nav-link not-clickable active" href="#">
                <i class="fas fa-database fa-fw"></i>
                Datasets
            </a>
        </li>
    {% for dataset in project.datasets %}
        <li class="nav-item">
            <a class="nav-link sidebar-link" data-toggle="collapse"
               href="#sidebar-{{ dataset.id }}-info">
                <i class="fas fa-caret-right fa-fw" id="sidebar-{{ dataset.id }}-toggle"></i>
                {{ dataset.name }}
            </a>
        </li>
        <!-- Collapsable dataset info card -->
        <div class="collapse sidebar-collapse" id="sidebar-{{ dataset.id }}-info">
            <div class="card card-body sidebar-card">
                <h6>Description:</h6>
                {{ dataset.description }}
                <hr/>
                <div class="row-fluid inline action-icons">
                    <!-- Open project button -->
                    <a href="{{ url_for('view_bp.view', dataset_id=dataset.id) }}">
                        <i class="fas fa-folder-open"></i>
                    </a>
                    <!-- Edit project button -->
                    <a href="#edit-dataset-modal" data-toggle="modal"
                       data-target="#edit-dataset-modal"
                       data-projectid="{{ dataset.id }}"
                       data-title="{{ dataset.name }}"
                       data-description="{{ dataset.description }}">
                        <i class="fas fa-edit"></i>
                    </a>
                    <!-- Delete project button -->
                    <form id="delete-form-{{ dataset.id }}"
                          action="{{ url_for('upload_bp.delete', dataset_id=dataset.id) }}"
                          method="POST">
                        <input type="hidden" name="dataset_id"
                               value="{{ dataset.id }}">
                        <a href="#" onclick="document.getElementById('delete-form-{{ dataset.id }}').submit()">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
    </ul>
{% endblock %}

{% block main_content %}
<div class="jumbotron">
    <div class="row">
        <div class="container">
            <form method=post action="{{ url_for('upload_bp.zip', project_id=project.id) }}">
                <h2>Upload without joining:</h2>
                    <table id="upload-table" class="table table-bordered" width="100%">
                        <thead>
                            <tr>
                                <th>File</th>
                                <th>Name</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for file in files %}
                            <tr>
                                <td>
                                     <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="checkbox-{{ file }}">
                                            {{ file }}
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <input type="text" class="form-control" value="{{ name }}" name="name-{{ file }}" required>
                                </td>
                                <td>
                                    <input type="text" class="form-control" value="{{ description }}" name="description-{{ file }}" required>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                <h2>Join and upload:</h2>
                <table id="join_table" class="table table-bordered" width="100%">
                    <thead>
                    <tr>
                        <th>Left</th>
                        <th>Join type</th>
                        <th>Right</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <select class="custom-select file-select" id="file-left">
                                    <option value="" disabled selected>Select file</option>
                                    {% for file in files %}
                                        <option>{{ file }}</option>
                                    {% endfor %}
                                </select>
                                <hr/>
                                <select class="custom-select" id="column-left">
                                    <option value="" disabled selected>Select column</option>
                                    {# Dynamically genererated options #}
                                </select>
                            </td>
                            <td>
                                <select class="custom-select" id="join-type">
                                    <option>cross</option>
                                    <option>inner</option>
                                    <option>left outer</option>
                                    <option>right outer</option>
                                    <option>full outer</option>
                                </select>
                            </td>
                            <td>
                                <select class="custom-select file-select" id="file-right">
                                    <option value="" disabled selected>Select file</option>
                                    {% for file in files %}
                                        <option>{{ file }}</option>
                                    {% endfor %}
                                </select>
                                <hr/>
                                <select class="custom-select" id="column-right">
                                    <option value="" disabled selected>Select column</option>
                                    {# Dynamically genererated options #}
                                </select>
                            </td>
                            <td>
                                <input type="text" class="form-control" id="join-name">
                            </td>
                            <td>
                                <input type="text" class="form-control" id="join-description">
                            </td>
                            <td>
                                <button type="button" class="btn btn-info btn-block add-join-btn"><i class="fas fa-plus"></i></button>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button type="submit" class="btn btn-success pull-right" name="button" value="upload">
                    <i class="fas fa-upload"></i>
                    Upload
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block modals %}
{% include 'Data/Import/edit_modal.html' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/Data/Import/zip_join.js') }}"></script>
    <script src="{{ url_for('static', filename='js/Data/Import/edit_modal.js') }}"></script>
{% endblock %}