app/Data/models.py
from app import database as db
from datetime import datetime


class Dataset(db.Model):
    """
    Represents table holding dataset info
    """

    __tablename__ = 'dataset'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    original_data = db.Column(db.String(50), unique=True, nullable=False)
    working_copy = db.Column(db.String(50), unique=True, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    # View is parent of action, thus this relationship helper class
    actions = db.relationship(
        'Action',
        backref='dataset',
        lazy='dynamic',
        passive_deletes=True
    )

    # Dataset is child of project, thus this foreign key
    project_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'project.id',
            ondelete='CASCADE'
        )
    )

    def __init__(self, name, original, working, description, project):
        self.name = name
        self.original_data = original
        self.working_copy = working
        self.description = description
        self.project_id = project


class Action(db.Model):
    """ Vieze docstring """

    __tablename__ = 'action'

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    time = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    # Action is child of view, thus this foreign key
    dataset_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'dataset.id',
            ondelete='CASCADE'
        )
        , nullable=False
    )

    # Action is child of user, thus this foreign key
    user_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user_data.id',
            ondelete='SET NULL')
    )

    def __init__(self, description, dataset_id, user_id):
        self.description = description
        self.dataset_id = dataset_id
        self.user_id = user_id

app/Data/Import/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FileField, TextAreaField
from wtforms.validators import InputRequired, Length


class UploadForm(FlaskForm):
    """docstring for UploadForm"""

    file = FileField('File (.csv, .zip or .dump)',
                     validators=[InputRequired()]
                     )
    name = StringField('Name', validators=[InputRequired(), Length(max=50)])
    description = TextAreaField('Description',
                                validators=[InputRequired(), Length(max=255)])


class EditForm(FlaskForm):
    """docstring for UploadForm"""

    name = StringField('Name', validators=[InputRequired(), Length(max=50)])
    description = TextAreaField('Description',
                                validators=[InputRequired(), Length(max=255)])

app/Data/View/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired, Length


class DeleteForm(FlaskForm):
    """Represents form used for sharing projects"""
    condition = StringField(
        '',
        id='condition',
        validators=[InputRequired()]
    )

app/Data/Transform/controllers.py
from flask import (
    Blueprint,
    request,
    jsonify,
    redirect,
    url_for,
    render_template,
    flash,
    Response
)
from flask_login import login_required, current_user
from app.Data.operations import create_action, get_dataset_with_id
from app.Data.helpers import table_name_to_object, escape_quotes
from app.Data.Transform.operations import (
    restore_original,
    change_attribute_type,
    delete_rows,
    fill_null_with,
    fill_null_with_average,
    fill_null_with_median,
    rename_attribute,
    delete_attribute,
    one_hot_encode,
    normalize_attribute,
    discretize_width,
    discretize_eq_freq,
    find_replace,
    regex_find_replace,
    substring_find_replace,
    nullify_outliers,
    extract_from_date_time
)

_transform = Blueprint('transform_bp', __name__, url_prefix='/data/transform')


@_transform.route('/rename_column', methods=['POST'])
@login_required
def rename_column():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    new_name = escape_quotes(request.form['new_name'])
    try:
        rename_attribute(dataset.working_copy, col, new_name)
    except:
        flash('An unexpected error occured while renaming the column', 'danger')
    else:
        flash('Column renamed successfully.', 'success')
        create_action('Renamed column {0} to {1}'.format(col, new_name), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/delete_column', methods=['POST'])
@login_required
def delete_column():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    try:
        delete_attribute(dataset.working_copy, col)
    except:
        flash('Failed to delete column {0} from {1}'.format(col, dataset.working_copy), 'danger')
    else:
        flash('Column deleted successfully.', 'success')
        create_action('Deleted column {0}'.format(col), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/one_hot_encode_column', methods=['POST'])
@login_required
def one_hot_encode_column():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    try:
        one_hot_encode(dataset.working_copy, col)
    except:
        flash('An unexpected error occured while one-hot-encoding column {0}'.format(col), 'danger')
    else:
        flash('Column one-hot-encoded successfully.', 'success')
        create_action('One-hot-encoded {0}'.format(col), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/normalize_column', methods=['POST'])
@login_required
def normalize_column():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    try:
        normalize_attribute(dataset.working_copy, col)
    except:
        flash('An unexpected error occured while normalizing the column',
              'danger'
              )
    else:
        flash('Column normalized successfully.', 'success')
        create_action('Normalized {0}'.format(col), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/discretize_column', methods=['POST'])
@login_required
def discretize_column():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    column = request.form['column']
    intervals = request.form['intervals']

    try:
        if intervals == 'equal-distance':
            amount = request.form['amount-dist']
            discretize_width(dataset.working_copy, column, int(amount))
        elif intervals == 'equal-frequency':
            amount = request.form['amount-freq']
            discretize_eq_freq(dataset.working_copy, column, int(amount))
        else:
            edges = str(request.form['custom-edges'])
            edges = edges.replace(' ', '')
            edge_list = edges.split(',')
            if len(edge_list) < 2:
                raise ValueError
            for i in range(len(edge_list)):
                edge_list[i] = float(edge_list[i])
            discretize_width(dataset.working_copy, column, edge_list)

    except ValueError:
        flash('Invalid list of edges provided.', 'danger')
    except:
        flash('An unexpected error occured while discretizing the column', 'danger')
    else:
        flash('Column discretized successfully.', 'success')
        create_action('column {0} discretized'.format(column), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/delete_selection', methods=['POST'])
@login_required
def delete_selection():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    selected_data = request.form.getlist("data_id")
    table = table_name_to_object(dataset.working_copy)
    for data in selected_data:
        table.delete(table.c.index == data).execute()
    create_action(
        'deleted selected items',
        dataset.id,
        current_user.id
    )
    return redirect(request.referrer)


@_transform.route('/delete_predicate', methods=['POST'])
@login_required
def delete_predicate():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    table = table_name_to_object(dataset.working_copy)
    condition = ''
    columns = []
    conditions = []
    operators = []
    logics = []
    for i in request.form:
        if i.startswith('column'):
            columns.append(i)
        elif i.startswith('condition'):
            conditions.append(i)
        elif i.startswith('logical'):
            logics.append(i)
        elif i.startswith('operator'):
            operators.append(i)
    columns.sort()
    conditions.sort()
    logics.sort()
    operators.sort()
    for i in range(len(columns)):
        if i != len(columns) - 1:
            condition += '"' + request.form[columns[i + 1]] + '"'
            if request.form[operators[i + 1]] == 'CONTAINS':
                condition += ' ~ '
            elif request.form[operators[i + 1]] == 'NOT CONTIANS':
                condition += ' !~ '
            else:
                condition += request.form[operators[i + 1]]
            condition += '\'' + request.form[conditions[i + 1]] + '\''
            condition += ' ' + request.form[logics[i]] + ' '
        else:
            condition += '"' + request.form[columns[0]] + '"'
            if request.form[operators[0]] == 'CONTAINS':
                condition += ' ~ '
            elif request.form[operators[0]] == 'NOT CONTIANS':
                condition += ' !~ '
            else:
                condition += request.form[operators[0]]
            condition += '\'' + escape_quotes(request.form[conditions[0]]) + '\''

    try:
        if delete_rows(table.name, condition) is False:
            flash('no rows found with condition {0}'.format(condition), 'warning')
        else:
            flash('successfully deleted rows using condition {0}'.format(condition), 'success')
            create_action('rows deleted with condition {0}'.format(condition), dataset.id, current_user.id)
    except:
        flash('condition "{0}" not valid'.format(condition), 'danger')

    return redirect(request.referrer)


@_transform.route('/reset', methods=['GET'])
@login_required
def reset():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    try:
        restore_original(dataset.working_copy)
    except:
        flash('Failed to restore original', 'danger')
    else:
        flash('restored dataset to original state', 'success')
        create_action('restored dataset to original state', dataset.id, current_user.id)
    return redirect(request.referrer)


@_transform.route('/change_type', methods=['POST'])
@login_required
def change_type():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    table = table_name_to_object(dataset.working_copy)
    col = request.form['column']
    col = col[:col.find('(') - 1]
    new_type = request.form['type']
    if col != '' and new_type != '':
        try:
            change_attribute_type(table.name, col, new_type)
        except:
            flash('{0} could not be converted to {1}'.format(col, new_type), 'danger')
        else:
            flash('{0} successfully  converted to {1}'.format(col, new_type), 'success')
            create_action('type {0} changed to {1}'.format(col, new_type), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/remove_outliers', methods=['POST'])
@login_required
def remove_outliers():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    operator = request.form['outlier-operator']
    edge = escape_quotes(request.form['outlier-edge'])

    try:
        nullify_outliers(dataset.working_copy, col, edge, operator)
    except:
        flash('An unexpected error occured while removing outliers.', 'danger')
    else:
        flash('Outliers removed successfully.', 'success')
        create_action('Removed values from {0} if {1} {2}.'.format(col, operator, edge), dataset.id, current_user.id)

    return redirect(request.referrer)


@_transform.route('/find_and_replace', methods=['POST'])
@login_required
def find_and_replace():
    dataset = get_dataset_with_id(request.args.get('dataset_id'))
    col = request.form['column']
    find = escape_quotes(request.form['find'])
    match_mode = request.form['match-mode']
    replace = escape_quotes(request.form['replace'])
    try:
        if match_mode == 'full-match':
            find_replace(dataset.working_copy, col, find, replace)
        elif match_mode == 'substring-match':
            replace_mode = request.form['replace-mode']
            if replace_mode == 'full-replace':
                substring_find_replace(dataset.working_copy,
                                       col,
                                       find,
                                       replace,
                                       full=True)

app/templates/Data/Transform/change_type_modal.html
<div class="modal fade" id="change_type_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.change_type', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th>New type:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column">
                                    {% for column in columns %}
                                        <option>{{ column[0] }} ({{ column[1] }})</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td width="35%">
                                <select class="custom-select" name="type">
                                    <option></option>
                                    <option>INTEGER</option>
                                    <option>DOUBLE</option>
                                    <option>TEXT</option>
                                    <option>DATE</option>
                                    <option>TIMESTAMP</option>
                                </select>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-success btn-block">
                                    Apply
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/delete_column_modal.html
<div class="modal fade" id="delete_column_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.delete_column', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column">
                                    {% for column in columns %}
                                        <option>{{ column[0] }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-danger btn-block">
                                    Delete
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/delete_predicate_modal.html
<div class="modal fade" id="delete_predicate_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.delete_predicate', dataset_id=dataset.id) }}">
                    <table id="delete_table" class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column</th>
                            <th>Operator</th>
                            <th>Condition</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column0" id="column">
                                    {% for column in columns %}
                                        <option>{{ column[0] }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <select class="custom-select" name="operator0" id="operator">
                                    <option>=</option>
                                    <option>!=</option>
                                    <option>></option>
                                    <option>>=</option>
                                    <option><</option>
                                    <option><=</option>
                                    <option>CONTAINS</option>
                                    <option>NOT CONTAINS</option>
                                </select>
                            </td>
                            <td>
                                <input type="text" class="form-control" id="condition" name="condition0">
                            </td>
                            <td width="20%"></td>
                            <td>
                                <button type="button" class="btn btn-info btn-block add-delete-btn">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                <button type="submit" class="btn btn-success float-right">Execute</button>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/discretize_modal.html
<div class="modal fade" id="discretize_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.discretize_column', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th>Intervals:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column">
                                    {% for column in columns %}
                                        {% if
                                        column[1] == 'INTEGER' or
                                        column[1] == 'DOUBLE'
                                        %}
                                        <option>{{ column[0] }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </td>
                            <td width="50%">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <input type="radio" name="intervals" id="discretize-radio-1" value="equal-distance" required>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control" value="Equal Distance" readonly>
                                    <input type="text" name="amount-dist" id="amount-dist" class="form-control" placeholder="Amount">
                                </div>
                                <div class="input-group" style="padding-top: 15px">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <input type="radio" name="intervals" id="discretize-radio-2" value="equal-frequency" required>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control" value="Equal Frequency" readonly>
                                    <input type="text" name="amount-freq" id="amount-freq" class="form-control" placeholder="Amount">
                                </div>
                                <hr/>
                                <h6>Custom edges (comma separate):</h6>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <input type="radio" name="intervals" id="discretize-radio-3" required>
                                        </div>
                                    </div>
                                    <input type="text" name="custom-edges" class="form-control" id="custom-edges">
                                </div>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-success btn-block">
                                    Discretize
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/find_and_replace_modal.html
<div class="modal fade" id="find_and_replace_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.find_and_replace', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th>Find:</th>
                            <th>Replace:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" id="far_column_select" name="column" required>
                                    <option value="" disabled selected>Select Column...</option>
                                    {% for column in columns %}
                                        <option data-type="{{ column[1] }}">{{ column[0] }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <input type="text" class="form-control" name="find" required>
                                <div class="form-check" style="margin-top: 8px">
                                    <input class="form-check-input far-match-radio" type="radio" name="match-mode" id="full-match-radio" value="full-match" required>
                                    <label class="form-check-label" for="full-match-radio">
                                        Full match
                                    </label>
                                </div>
                                <div class="form-check" style="margin-top: 8px">
                                    <input class="form-check-input far-match-radio far-text-type-only" type="radio" name="match-mode" id="substring-match-radio" value="substring-match" required>
                                    <label class="form-check-label" for="substring-match-radio">
                                        Substring match*
                                    </label>
                                </div>
                                <div class="form-check" style="margin-top: 8px">
                                    <input class="form-check-input far-match-radio far-text-type-only" type="radio" name="match-mode" id="regex-match-radio" value="regex-match" required>
                                    <label class="form-check-label" for="regex-match-radio">
                                        Regex match*
                                    </label>
                                </div>
                            </td>
                            <td>
                                <input type="text" class="form-control" name="replace">
                                <div class="form-check" style="margin-top: 8px">
                                    <input class="form-check-input far-replace-radio" type="radio" name="replace-mode" id="full-replace-radio" value="full-replace" disabled>
                                    <label class="form-check-label" for="full-replace-radio">
                                        Full replace
                                    </label>
                                </div>
                                <div class="form-check" style="margin-top: 8px">
                                    <input class="form-check-input far-replace-radio" type="radio" name="replace-mode" id="substring-replace-radio" value="substring-replace" disabled>
                                    <label class="form-check-label" for="substring-replace-radio">
                                        Substring replace
                                    </label>
                                </div>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-success btn-block">
                                    Execute
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <span class="text-muted">*Only supported for text types.</span>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/normalize_modal.html
<div class="modal fade" id="normalize_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.normalize_column', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column">
                                    {% for column in columns %}
                                        {% if
                                        column[1] == 'INTEGER' or
                                        column[1] == 'DOUBLE'
                                        %}
                                        <option>{{ column[0] }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-success btn-block">
                                    Normalize
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/Data/Transform/one_hot_encode_modal.html
<div class="modal fade" id="one_hot_encode_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action="{{ url_for('transform_bp.one_hot_encode_column', dataset_id=dataset.id) }}">
                    <table class="table" width="100%">
                        <thead>
                        <tr class="table-primary">
                            <th>Column:</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="custom-select" name="column">
                                    {% for column in columns %}
                                        {% if column[1] == 'TEXT' %}
                                        <option>{{ column[0] }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </td>
                            <td width="5%">
                                <button type="submit" class="btn btn-success btn-block">
                                    Encode
                                </button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>